import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth, currentUser } from "@clerk/nextjs/server";
import { z } from "zod";
import { rateLimit } from "@/lib/rate-limit";
import { Prisma } from "@prisma/client";
import { cookies } from "next/headers";

// Domain errors

class AccountDisabledError extends Error {
  readonly code = "ACCOUNT_DISABLED";
  constructor() {
    super("Account disabled");
    this.name = "AccountDisabledError";
  }
}

class EmailConflictError extends Error {
  readonly code = "EMAIL_CONFLICT";
  constructor() {
    super("Email already registered to another account");
    this.name = "EmailConflictError";
  }
}

// Validation

const userUpdateSchema = z.object({
  name: z
    .string()
    .max(100)
    .trim()
    .transform((v) => v.replace(/\s+/g, " ").normalize("NFKC"))
    .refine((v) => v.trim().length >= 2, "Name must be at least 2 characters"),
  address: z
    .string()
    .max(255)
    .trim()
    .optional()
    .transform((v) => (v && v.length > 0 ? v : null)),
});

// Cookie helpers

function onboardingCookieOptions() {
  return {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax" as const,
    maxAge: 60 * 60 * 24 * 365,
    path: "/",
  };
}

// POST /api/user

export async function POST(request: Request) {
  // rateLimit is async must be awaited. The original code did NOT
  // await it, so `limited` was always a truthy Promise object, meaning rate
  // limiting was completely bypassed on this endpoint.
  const limited = await rateLimit(request, { windowMs: 60000, max: 5 });
  if (limited) return limited;

  let userId: string | null = null;

  try {
    const auth_ = await auth();
    userId = auth_.userId;
    const sessionId = auth_.sessionId;

    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    let body: unknown;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
    }

    const parsed = userUpdateSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json({ error: parsed.error.issues }, { status: 400 });
    }

    // Explicit allow-list — never spread parsed.data into a Prisma write.
    const { name, address } = parsed.data;

    const clerkUser = await currentUser();
    const email = clerkUser?.primaryEmailAddress?.emailAddress;

    if (!clerkUser || !email) {
      console.error("POST /api/user — Clerk user or email missing", { userId });
      return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
    }

    const user = await prisma.$transaction(async (tx) => {
      // use clerkId for all lookups. The upsert uses clerkId as the
      // unique selector; the internal `id` is generated by Prisma (@default(cuid())).
      const existing = await tx.user.findUnique({
        where: { clerkId: userId! },
        select: { id: true, isActive: true, email: true },
      });

      if (existing?.isActive === false) throw new AccountDisabledError();

      if (!existing) {
        const emailOwner = await tx.user.findUnique({
          where: { email },
          select: { clerkId: true },
        });
        if (emailOwner && emailOwner.clerkId !== userId!) throw new EmailConflictError();
      }

      return tx.user.upsert({
        where: { clerkId: userId! },
        update: {
          name,
          address,
          hasCompletedOnboarding: true,
          // role and isActive are intentionally absent — immutable via this route.
        },
        create: {
          // id is omitted — Prisma generates a cuid() automatically.
          clerkId: userId!,
          email,
          name,
          address,
          role: "CUSTOMER",
          isActive: true,
          hasCompletedOnboarding: true,
        },
        select: {
          id: true,
          email: true,
          name: true,
          address: true,
          role: true,
          isActive: true,
          hasCompletedOnboarding: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    });

    const response = NextResponse.json({ data: user });
    const cookieStore = await cookies();
    cookieStore.set("onboarding_complete", "1", onboardingCookieOptions());
    if (sessionId) {
      cookieStore.set("ob_verified", sessionId, {
        httpOnly: true,
        secure: process.env.NODE_ENV === "production",
        sameSite: "lax",
        path: "/",
      });
    }
    return response;
  } catch (error) {
    if (error instanceof AccountDisabledError) {
      return NextResponse.json(
        { error: "Account disabled", code: "ACCOUNT_DISABLED" },
        { status: 403 }
      );
    }
    if (error instanceof EmailConflictError) {
      return NextResponse.json(
        { error: error.message, code: "EMAIL_CONFLICT" },
        { status: 409 }
      );
    }
    if (
      error instanceof Prisma.PrismaClientKnownRequestError &&
      error.code === "P2002"
    ) {
      return NextResponse.json(
        { error: "Email already registered to another account", code: "EMAIL_CONFLICT" },
        { status: 409 }
      );
    }
    console.error("POST /api/user", { userId, error });
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}

// GET /api/user

export async function GET() {
  let userId: string | null = null;

  try {
    const auth_ = await auth();
    userId = auth_.userId;

    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const user = await prisma.user.findUnique({
      // look up by clerkId, not by internal id.
      where: { clerkId: userId },
      select: {
        id: true,
        email: true,
        name: true,
        address: true,
        role: true,
        isActive: true,
        hasCompletedOnboarding: true,
        createdAt: true,
        updatedAt: true,
      },
    });

    if (!user) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    if (!user.isActive) {
      return NextResponse.json(
        { error: "Account disabled", code: "ACCOUNT_DISABLED" },
        { status: 403 }
      );
    }

    return NextResponse.json({ data: user });
  } catch (error) {
    console.error("GET /api/user", { userId, error });
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}